export const ITEMTYPES = [
    { value: "simple weapon", description: "Simple Weapon" },
    { value: "martial weapon", description: "Martial Weapon" },
    { value: "light armor", description: "Light Armor" },
    { value: "medium armor", description: "Medium Armor" },
    { value: "heavy armor", description: "Heavy Armor" },
    { value: "shield", description: "Shield" },
    { value: "potion", description: "Potion" },
    { value: "ring", description: "Ring" },
    { value: "wondrous item", description: "Wondrous Item" },
    { value: "staff", description: "Staff" },
    { value: "wand", description: "Wand" },
    { value: "scroll", description: "Scroll" },
    { value: "ammunition", description: "Ammunition" },
    { value: "adventuring gear", description: "Adventuring Gear" },
    { value: "tool", description: "Tool" },
    { value: "instrument", description: "Instrument" },
    { value: "consumable", description: "Consumable" },
    { value: "gem", description: "Gem" },
    { value: "treasure", description: "Treasure" },
]

export const DAMAGETYPES = [
    { value: "none", description: "None" },
    { value: "bludgeoning", description: "Bludgeoning" },
    { value: "piercing", description: "Piercing" },
    { value: "slashing", description: "Slashing" },
    { value: "acid", description: "Acid" },
    { value: "cold", description: "Cold" },
    { value: "fire", description: "Fire" },
    { value: "force", description: "Force" },
    { value: "lightning", description: "Lightning" },
    { value: "necrotic", description: "Necrotic" },
    { value: "poison", description: "Poison" },
    { value: "psychic", description: "Psychic" },
    { value: "radiant", description: "Radiant" },
    { value: "thunder", description: "Thunder" },
]

export const CONDITIONS = [
    { name: "Blinded", description: "A blinded creature can't see and automatically fails any ability check that requires sight. Attack rolls against the creature have advantage, and the creature's attack rolls have disadvantage." },
    { name: "Charmed", description: "A charmed creature can't attack the charmer or target the charmer with harmful abilities or magical effects. The charmer has advantage on any ability check to interact socially with the creature." },
    { name: "Deafened", description: "A deafened creature can't hear and automatically fails any ability check that requires hearing." },
    { name: "Frightened", description: "A frightened creature has disadvantage on ability checks and attack rolls while the source of its fear is within line of sight. The creature can't willingly move closer to the source of its fear." },
    { name: "Grappled", description: "A grappled creature's speed becomes 0, and it can't benefit from any bonus to its speed. The condition ends if the grappler is incapacitated or the creature is removed from the grappler's reach." },
    { name: "Incapacitated", description: "An incapacitated creature can't take actions or reactions." },
    { name: "Invisible", description: "An invisible creature is impossible to see without the aid of magic or a special sense. Attack rolls against the creature have disadvantage, and the creature's attack rolls have advantage." },
    { name: "Paralyzed", description: "A paralyzed creature is incapacitated and can't move or speak. Automatically fails Strength and Dexterity saving throws. Attack rolls against the creature have advantage. Attacks within 5 feet are critical hits." },
    { name: "Petrified", description: "A petrified creature is transformed into a solid inanimate substance. Incapacitated, can't move or speak, and unaware of surroundings. Automatically fails Strength and Dexterity saving throws. Resistant to all damage. Immune to poison and disease." },
    { name: "Poisoned", description: "A poisoned creature has disadvantage on attack rolls and ability checks." },
    { name: "Prone", description: "A prone creature can only crawl unless it stands. Attack rolls have advantage within 5 feet, otherwise disadvantage." },
    { name: "Restrained", description: "Speed becomes 0, can't benefit from bonus to speed. Attack rolls against have advantage, creature's attacks have disadvantage. Disadvantage on Dex saves." },
    { name: "Stunned", description: "Incapacitated, can't move, speaks falteringly. Automatically fails Strength and Dex saves. Attack rolls against have advantage." },
    { name: "Unconscious", description: "Incapacitated, can't move or speak, unaware of surroundings. Drops held items and falls prone. Automatically fails Strength and Dex saves. Attacks within 5 feet are critical hits." },
]